INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (1, 'Rob Siltanen');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (2, 'Albert Einstein');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (3, 'Charles Eames');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (4, 'Henry Ford');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (5, 'Antoine de Saint-Exupery');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (6, 'Salvador Dali');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (7, 'M.C. Escher');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (8, 'Paul Rand');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (9, 'Elon Musk');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (10, 'Jessica Hische');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (11, 'Paul Rand');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (12, 'Mark Weiser');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (13, 'Pablo Picasso');
INSERT INTO randomquotes.author (ID, AUTHOR) VALUES (14, 'Charles Mingus');

INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (1, 1, 'Here''s to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They''re not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can''t do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (2, 2, 'Everything should be made as simple as possible, but not simpler.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (3, 3, 'Here is one of the few effective keys to the design problem: the ability of the designer to recognize as many of the constraints as possible; his willingness and enthusiasm for working within these constraints.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (4, 4, 'If I had asked people what they wanted, they would have said faster horses.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (5, 5, 'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (6, 6, 'Have no fear of perfection, you''ll never reach it.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (7, 7, 'Only those who attempt the absurd will achieve the impossible.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (8, 8, 'Design is so simple. That''s why it''s so complicated.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (9, 9, 'Any product that needs a manual to work is broken.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (10, 10, 'The work you do while you procrastinate is probably the work you should be doing for the rest of your life.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (11, 11, 'Simplicity is not the goal. It is the by-product of a good idea and modest expectations.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (12, 12, 'The most profound technologies are those that disappear. They weave themselves into the fabric of everyday life until they are indistinguishable from it.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (13, 13, 'Every child is an artist, the problem is staying an artist when you grow up.');
INSERT INTO randomquotes.quote (ID, AUTHOR_ID, QUOTE) VALUES (14, 14, 'Creativity is more than just being different. Anybody can plan weird; that''s easy. What''s hard is to be as simple as Bach. Making the simple, awesomely simple, that''s creativity.');