name: Deploy Website

on:
  push:
    branches: 
      - master

env:  
  PACKAGES_FOLDER: Modules
  OUTPUT_FOLDER: PackagesOutput
  PACKAGE_NAME: randomquotes
  OCTOPUS_PROJECT_NAME: RandomQuotes  
  OCTOPUS_SPACE_NAME: JeremyM
  ENVIRONMENT: Development
  CHANNEL: Default

jobs:
  build:
    name: Build and Push Website

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Setup Java JDK
    #  uses: actions/setup-java@v2.4.0
    #  with:
    #      java-version: '11'
    #      distribution: 'adopt'
    
    - name: Set environment variables
      run: |
        $branchName = ((${env:GITHUB_REF} -replace "refs/heads/", "") -replace "feature/", "") -replace "bugfix/", ""
        Write-Host "$branchName"  

        $versionFromFile = "1.0"
        Write-Host "Found $versionFromFile in versionprefix.md"
        $versionNumber = "$versionfromFile.${{ github.RUN_NUMBER }}"
        $channelName = "Default"
        $deployEnvironment = "Development"
        $mergedBranch = ""

        $commitMessage = git log -1 --pretty=oneline
        Write-Host "The commit message is: $commitMessage"

        if ($branchName -ne "master")
        {
           $versionNumber = "2020.99.99.${{env.GITHUB_RUN_NUMBER}}"
           $versionNumber = "$versionNumber-$branchName"
           $channelName = "Feature Branches"
           $deployEnvironment = "Test"           
        }
        elseif ($branchName -eq "master" -and $commitMessage -like "*Merge pull request*")
        {          
          $indexOfSlash = $commitMessage.ToString().IndexOf('/')
          Write-Host "The index of the slash is $indexOfSlash"
          $mergedBranch = $commitMessage.SubString($commitMessage.IndexOf("/") + 1)
          Write-Host "The merged branch before replacement is $mergedBranch"
          $mergedBranch = ($mergedBranch -replace "feature/", "") -replace "bugfix/", ""          
          Write-Host "The merged branch is now $mergedBranch"
        }

        Write-Host "Setting environment variable PACKAGE_VERSION to: $versionNumber"
        Write-Host "Setting environment variable BRANCH_NAME to: $branchName"
        Write-Host "Setting environment variable CHANNEL_NAME to: $channelName"
        Write-Host "Setting environment variable ENVIRONMENT_NAME to: $deployEnvironment"
        Write-Host "Setting environment variable MERGED_BRANCH to: $mergedBranch"
        echo "BRANCH_NAME=$branchName" | Out-File -FilePath $env:GITHUB_ENV  -Append
        echo "PACKAGE_VERSION=$versionNumber" | Out-File -FilePath $env:GITHUB_ENV  -Append
        echo "CHANNEL_NAME=$channelName" | Out-File -FilePath $env:GITHUB_ENV  -Append
        echo "ENVIRONMENT_NAME=$deployEnvironment" | Out-File -FilePath $env:GITHUB_ENV  -Append
        echo "MERGED_BRANCH=$mergedBranch" | Out-File -FilePath $env:GITHUB_ENV  -Append
      shell: pwsh
    
    - name: Build Website
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      run: |
        mvn versions:set -DnewVersion=1.0.${{ github.RUN_NUMBER }}
        mvn clean test package -Pwar
        cd target
        Rename-Item -Path "${{ env.PACKAGE_NAME }}.1.war" -NewName "${{ env.PACKAGE_NAME }}.1.0.${{ github.RUN_NUMBER }}.war"
      shell: pwsh
      
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest
      
    - name: Push Package to Octopus Deploy
      uses: OctopusDeploy/push-package-action@v1.1.1
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        log_level: verbose
        overwrite_mode: OverwriteExisting
        packages: ${{ github.WORKSPACE }}/target/${{ env.PACKAGE_NAME }}.1.0.${{ github.RUN_NUMBER }}.war
        server: ${{ secrets.OCTOPUS_URL }}
        space: ${{ env.OCTOPUS_SPACE_NAME }}

    - name: Push Build Information
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}        
      run: |
        Write-Host "Building the build information"   
        $commitMessage = git log -1 --pretty=oneline
        $commitMessage = $commitMessage -replace "${{ github.SHA }} ", ""
        Write-Host "Commit Message: $commitMessage"        

        $jsonBody = @{
          BuildEnvironment = "GitHub Actions"
          Branch = "${{ github.REF_NAME }}"
          BuildNumber = "${{ github.RUN_NUMBER }}"
          BuildUrl = "https://github.com/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}"
          VcsCommitNumber = "${{ github.SHA }}"
          VcsType = "Git"
          VcsRoot = "https://github.com/${{ github.REPOSITORY }}.git"
          Commits = @(
            @{
              Id = "${{ github.SHA }}"
              LinkUrl = "https://github.com/${{ github.REPOSITORY }}/commit/${{ github.SHA }}"
              Comment = "$commitMessage"
            }
          )
        } | ConvertTo-Json -Depth 10

        New-Item "buildinformation.json" -ItemType File
        Set-Content -Path "buildinformation.json" -Value $jsonBody
        octo build-information --package-id="${{ env.PACKAGE_NAME }}" --file="buildinformation.json" --version="1.0.${{ github.RUN_NUMBER }}" --server="${{ env.OCTOPUS_URL }}" --apiKey="${{ env.OCTOPUS_API_KEY }}" --space="${{ env.OCTOPUS_SPACE_NAME }}"
     
      shell: pwsh
      
    - name: Create Release in Octopus Deploy
      uses: OctopusDeploy/create-release-action@v1.1.1
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        channel: ${{ env.CHANNEL }}
        deploy_to: ${{ env.ENVIRONMENT }}
        log_level: verbose
        package_version: 1.0.${{ github.RUN_NUMBER }}
        project: ${{ env.OCTOPUS_PROJECT_NAME }}
        release_number: 1.0.${{ github.RUN_NUMBER }}
        server: ${{ secrets.OCTOPUS_URL }}
        space: ${{ env.OCTOPUS_SPACE_NAME }}
    
