name: Output Vars

on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  build:
    name: Test Output Vars

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    #- shell: pwsh
      #run: echo "mypath" | Out-File -FilePath $env:GITHUB_PATH -Append # no need for -Encoding utf8
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "action_state2=red" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: pwsh
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
        echo "${{ env.action_state2 }}" # This will output 'red'
      shell: pwsh
      
